name: Shared

on:
  workflow_call:
    inputs:
      angular_package_version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  build_dotnet:
    name: Build .NET projects

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install wasm tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Cleanup wasm
      run: rm -rf src/Smusdi.Wasm/bin && rm -rf src/Smusdi.Wasm/obj
    - name: Building wasm
      run: dotnet publish src/Smusdi.Wasm/Smusdi.Wasm.csproj --configuration Release -p:Version=${{ inputs.angular_package_version }}
    - uses: actions/upload-artifact@v4
      with:
        name: smusdi-wasm
        path: src/Smusdi.Wasm/bin/Release/net8.0/browser-wasm/AppBundle
        retention-days: 2
  
  build_angular:
    name: Build angular packages
    needs: build_dotnet

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: smusdi-wasm
        path: ui/projects/ngssm-regex-tools/assets
    - run: ls -lrt ui/projects/ngssm-regex-tools/assets
    - uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: 'ui/package-lock.json'
    - run: cd ui && npm ci
    - run: cd ui && npm run build:ci
    - run: cd ui && npm run build
    - run: cd ui && npm run test:ci
    - run: cp README.md ui/dist/ngssm-regex-tools/.
    - run: |
        cd ui/dist/ngssm-regex-tools
        npm version ${{ inputs.angular_package_version }}
        npm pack
    - uses: actions/upload-artifact@v4
      with:
        name: ngssm-regex-tools
        path: ui/dist/ngssm-regex-tools/ngssm-regex-tools-${{ inputs.angular_package_version }}.tgz
        retention-days: 2
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ui/coverage/**/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - run: mv code-coverage-results.md angular-code-coverage-results.md
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        header: angular
        message: angular coverage
        recreate: true
        path: angular-code-coverage-results.md


